/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmesIndexRouteImport } from './routes/filmes/index'
import { Route as FilmesMovieIdRouteRouteImport } from './routes/filmes/$movieId/route'
import { Route as FilmesNovoRouteImport } from './routes/filmes/novo'
import { Route as FilmesMovieIdIndexRouteImport } from './routes/filmes/$movieId/index'
import { Route as FilmesMovieIdEditarRouteImport } from './routes/filmes/$movieId/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesIndexRoute = FilmesIndexRouteImport.update({
  id: '/filmes/',
  path: '/filmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesMovieIdRouteRoute = FilmesMovieIdRouteRouteImport.update({
  id: '/filmes/$movieId',
  path: '/filmes/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesNovoRoute = FilmesNovoRouteImport.update({
  id: '/filmes/novo',
  path: '/filmes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesMovieIdIndexRoute = FilmesMovieIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmesMovieIdRouteRoute,
} as any)
const FilmesMovieIdEditarRoute = FilmesMovieIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => FilmesMovieIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filmes/$movieId': typeof FilmesMovieIdRouteRouteWithChildren
  '/filmes/novo': typeof FilmesNovoRoute
  '/filmes/': typeof FilmesIndexRoute
  '/filmes/$movieId/editar': typeof FilmesMovieIdEditarRoute
  '/filmes/$movieId/': typeof FilmesMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filmes/novo': typeof FilmesNovoRoute
  '/filmes': typeof FilmesIndexRoute
  '/filmes/$movieId/editar': typeof FilmesMovieIdEditarRoute
  '/filmes/$movieId': typeof FilmesMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filmes/$movieId': typeof FilmesMovieIdRouteRouteWithChildren
  '/filmes/novo': typeof FilmesNovoRoute
  '/filmes/': typeof FilmesIndexRoute
  '/filmes/$movieId/editar': typeof FilmesMovieIdEditarRoute
  '/filmes/$movieId/': typeof FilmesMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/filmes/$movieId'
    | '/filmes/novo'
    | '/filmes/'
    | '/filmes/$movieId/editar'
    | '/filmes/$movieId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/filmes/novo'
    | '/filmes'
    | '/filmes/$movieId/editar'
    | '/filmes/$movieId'
  id:
    | '__root__'
    | '/'
    | '/filmes/$movieId'
    | '/filmes/novo'
    | '/filmes/'
    | '/filmes/$movieId/editar'
    | '/filmes/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmesMovieIdRouteRoute: typeof FilmesMovieIdRouteRouteWithChildren
  FilmesNovoRoute: typeof FilmesNovoRoute
  FilmesIndexRoute: typeof FilmesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/': {
      id: '/filmes/'
      path: '/filmes'
      fullPath: '/filmes/'
      preLoaderRoute: typeof FilmesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/$movieId': {
      id: '/filmes/$movieId'
      path: '/filmes/$movieId'
      fullPath: '/filmes/$movieId'
      preLoaderRoute: typeof FilmesMovieIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/novo': {
      id: '/filmes/novo'
      path: '/filmes/novo'
      fullPath: '/filmes/novo'
      preLoaderRoute: typeof FilmesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/$movieId/': {
      id: '/filmes/$movieId/'
      path: '/'
      fullPath: '/filmes/$movieId/'
      preLoaderRoute: typeof FilmesMovieIdIndexRouteImport
      parentRoute: typeof FilmesMovieIdRouteRoute
    }
    '/filmes/$movieId/editar': {
      id: '/filmes/$movieId/editar'
      path: '/editar'
      fullPath: '/filmes/$movieId/editar'
      preLoaderRoute: typeof FilmesMovieIdEditarRouteImport
      parentRoute: typeof FilmesMovieIdRouteRoute
    }
  }
}

interface FilmesMovieIdRouteRouteChildren {
  FilmesMovieIdEditarRoute: typeof FilmesMovieIdEditarRoute
  FilmesMovieIdIndexRoute: typeof FilmesMovieIdIndexRoute
}

const FilmesMovieIdRouteRouteChildren: FilmesMovieIdRouteRouteChildren = {
  FilmesMovieIdEditarRoute: FilmesMovieIdEditarRoute,
  FilmesMovieIdIndexRoute: FilmesMovieIdIndexRoute,
}

const FilmesMovieIdRouteRouteWithChildren =
  FilmesMovieIdRouteRoute._addFileChildren(FilmesMovieIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmesMovieIdRouteRoute: FilmesMovieIdRouteRouteWithChildren,
  FilmesNovoRoute: FilmesNovoRoute,
  FilmesIndexRoute: FilmesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
